#!/bin/sh
adduser --home-dir /home/$1 --uid 1002 $1
usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $1
usermod -aG docker $1

mkdir -p /home/$1/.local/share/docker
chown -R $1:$1 /home/$1/.local/share/docker