FROM docker.mobilesolutionworks.com/redhat/ubi8

RUN dnf install -y \
    wget \
    rpm-build \
    git
    
RUN wget https://github.com/nektos/act/releases/download/v0.2.68/act_Linux_arm64.tar.gz \
    && tar xfvz act_Linux_arm64.tar.gz \
    && mv act /usr/bin \
    && rm -rf act_Linux_arm64.tar.gz

RUN wget https://nodejs.org/dist/v20.17.0/node-v20.17.0-linux-x64.tar.xz \
    && mkdir -p /usr/lib \
    && tar xf node-v20.17.0-linux-x64.tar.xz \
    && mv node-v20.17.0-linux-x64 /usr/lib/node \
    && rm node-v20.17.0-linux-x64.tar.xz

ENV PATH=$PATH:/usr/lib/node/bin

ADD files /

RUN dnf install -y createrepo \
    && rm -rf /etc/yum.repos.d/ol8.repo

RUN dnf install -y mobilesolutionworks-dind-rootless \
    && chmod -R +x /usr/local/bin

ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh"]